[package]
name = "gb_emu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

winit = "*"
winit_input_helper = "*"
pixels = "*"

egui = "*"
egui-wgpu = "*"
egui-winit = { version = "*", default-features = false, features = ["links"]}

log = "*"
env_logger = "*"

spin_sleep = "1.1.1"
